// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// psi_cpp
NumericVector psi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_psi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(psi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}

// dpsi_cpp
NumericVector dpsi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_dpsi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(dpsi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}

// Psi_cpp
NumericVector Psi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_Psi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(Psi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}

// ddpsi_cpp
NumericVector ddpsi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_ddpsi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(ddpsi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}

// compute_G_in_vectorized_cpp
NumericMatrix compute_G_in_vectorized_cpp(int i, NumericMatrix X, NumericMatrix Y, NumericMatrix Z, double tau);
RcppExport SEXP _cgrdpg_compute_G_in_vectorized_cpp(SEXP iSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_G_in_vectorized_cpp(i, X, Y, Z, tau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cgrdpg_psi_cpp", (DL_FUNC) &_cgrdpg_psi_cpp, 2},
    {"_cgrdpg_dpsi_cpp", (DL_FUNC) &_cgrdpg_dpsi_cpp, 2},
    {"_cgrdpg_Psi_cpp", (DL_FUNC) &_cgrdpg_Psi_cpp, 2},
    {"_cgrdpg_ddpsi_cpp", (DL_FUNC) &_cgrdpg_ddpsi_cpp, 2},
    {"_cgrdpg_compute_G_in_vectorized_cpp", (DL_FUNC) &_cgrdpg_compute_G_in_vectorized_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_cgrdpg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
