// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_G_cpp
NumericMatrix compute_G_cpp(int i, NumericMatrix X, NumericMatrix Y, NumericMatrix Z, NumericVector w);
RcppExport SEXP _cgrdpg_compute_G_cpp(SEXP iSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_G_cpp(i, X, Y, Z, w));
    return rcpp_result_gen;
END_RCPP
}
// compute_gradient_cpp
NumericVector compute_gradient_cpp(int i, NumericVector A, NumericMatrix X, NumericMatrix Y, NumericMatrix Z, NumericVector B, NumericVector s, NumericVector w);
RcppExport SEXP _cgrdpg_compute_gradient_cpp(SEXP iSEXP, SEXP ASEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP BSEXP, SEXP sSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gradient_cpp(i, A, X, Y, Z, B, s, w));
    return rcpp_result_gen;
END_RCPP
}
// compute_G_in_vectorized_cpp
NumericMatrix compute_G_in_vectorized_cpp(int i, NumericMatrix X, NumericMatrix Y, NumericMatrix Z, double tau);
RcppExport SEXP _cgrdpg_compute_G_in_vectorized_cpp(SEXP iSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_G_in_vectorized_cpp(i, X, Y, Z, tau));
    return rcpp_result_gen;
END_RCPP
}
// psi1_cpp
NumericVector psi1_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_psi1_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(psi1_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// psi2_cpp
NumericVector psi2_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_psi2_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(psi2_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// psi_cpp
NumericVector psi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_psi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(psi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}
// dpsi1_cpp
NumericVector dpsi1_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_dpsi1_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(dpsi1_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// dpsi2_cpp
NumericVector dpsi2_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_dpsi2_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(dpsi2_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// dpsi_cpp
NumericVector dpsi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_dpsi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(dpsi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}
// ddpsi1_cpp
NumericVector ddpsi1_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_ddpsi1_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(ddpsi1_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// ddpsi2_cpp
NumericVector ddpsi2_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_ddpsi2_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(ddpsi2_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// ddpsi_cpp
NumericVector ddpsi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_ddpsi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(ddpsi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}
// Psi1_cpp
NumericVector Psi1_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_Psi1_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(Psi1_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// Psi2_cpp
NumericVector Psi2_cpp(NumericVector x, double tau);
RcppExport SEXP _cgrdpg_Psi2_cpp(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(Psi2_cpp(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// Psi_cpp
NumericVector Psi_cpp(NumericVector s, double tau);
RcppExport SEXP _cgrdpg_Psi_cpp(SEXP sSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(Psi_cpp(s, tau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cgrdpg_compute_G_cpp", (DL_FUNC) &_cgrdpg_compute_G_cpp, 5},
    {"_cgrdpg_compute_gradient_cpp", (DL_FUNC) &_cgrdpg_compute_gradient_cpp, 8},
    {"_cgrdpg_compute_G_in_vectorized_cpp", (DL_FUNC) &_cgrdpg_compute_G_in_vectorized_cpp, 5},
    {"_cgrdpg_psi1_cpp", (DL_FUNC) &_cgrdpg_psi1_cpp, 2},
    {"_cgrdpg_psi2_cpp", (DL_FUNC) &_cgrdpg_psi2_cpp, 2},
    {"_cgrdpg_psi_cpp", (DL_FUNC) &_cgrdpg_psi_cpp, 2},
    {"_cgrdpg_dpsi1_cpp", (DL_FUNC) &_cgrdpg_dpsi1_cpp, 2},
    {"_cgrdpg_dpsi2_cpp", (DL_FUNC) &_cgrdpg_dpsi2_cpp, 2},
    {"_cgrdpg_dpsi_cpp", (DL_FUNC) &_cgrdpg_dpsi_cpp, 2},
    {"_cgrdpg_ddpsi1_cpp", (DL_FUNC) &_cgrdpg_ddpsi1_cpp, 2},
    {"_cgrdpg_ddpsi2_cpp", (DL_FUNC) &_cgrdpg_ddpsi2_cpp, 2},
    {"_cgrdpg_ddpsi_cpp", (DL_FUNC) &_cgrdpg_ddpsi_cpp, 2},
    {"_cgrdpg_Psi1_cpp", (DL_FUNC) &_cgrdpg_Psi1_cpp, 2},
    {"_cgrdpg_Psi2_cpp", (DL_FUNC) &_cgrdpg_Psi2_cpp, 2},
    {"_cgrdpg_Psi_cpp", (DL_FUNC) &_cgrdpg_Psi_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_cgrdpg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
