# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psi_cpp <- function(s, tau = 0.05) {
    .Call('_cgrdpg_psi_cpp', PACKAGE = 'cgrdpg', s, tau)
}

dpsi_cpp <- function(s, tau = 0.05) {
    .Call('_cgrdpg_dpsi_cpp', PACKAGE = 'cgrdpg', s, tau)
}

Psi_cpp <- function(s, tau = 0.05) {
    .Call('_cgrdpg_Psi_cpp', PACKAGE = 'cgrdpg', s, tau)
}

ddpsi_cpp <- function(s, tau = 0.05) {
    .Call('_cgrdpg_ddpsi_cpp', PACKAGE = 'cgrdpg', s, tau)
}

compute_G_in_vectorized_cpp <- function(i, X, Y, Z, tau = 0.005) {
    .Call('_cgrdpg_compute_G_in_vectorized_cpp', PACKAGE = 'cgrdpg', i, X, Y, Z, tau)
}
