# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Fisher information matrix G_in for a single vertex (C++ version)
#'
#' @param i vertex index (0-based in C++)
#' @param X matrix of latent positions (n x d)
#' @param Y matrix Y = X * sign_diag (n x d)
#' @param Z covariate loading matrix (p_cov x d)
#' @param w vector of weights from dpsi (length n)
#' @return d x d Fisher information matrix
#' @export
compute_G_cpp <- function(i, X, Y, Z, w) {
    .Call(`_cgrdpg_compute_G_cpp`, i, X, Y, Z, w)
}

#' Compute gradient (score function) for a single vertex (C++ version)
#'
#' @param i vertex index (0-based in C++)
#' @param A adjacency vector for vertex i (length n)
#' @param X matrix of latent positions (n x d)
#' @param Y matrix Y = X * sign_diag (n x d)
#' @param Z covariate loading matrix (p_cov x d)
#' @param B covariate vector for vertex i (length p_cov)
#' @param s vector of inner products (length n)
#' @param w vector of weights from dpsi (length n)
#' @return d-dimensional gradient vector
#' @export
compute_gradient_cpp <- function(i, A, X, Y, Z, B, s, w) {
    .Call(`_cgrdpg_compute_gradient_cpp`, i, A, X, Y, Z, B, s, w)
}

#' Vectorized computation of G_in matrix (optimized C++ version)
#'
#' @param i vertex index (0-based)
#' @param X matrix of latent positions (n x d)
#' @param Y matrix Y = X * sign_diag (n x d)
#' @param Z covariate loading matrix (p_cov x d)
#' @param tau smoothing parameter
#' @return d x d matrix G_in
#' @export
compute_G_in_vectorized_cpp <- function(i, X, Y, Z, tau = 0.005) {
    .Call(`_cgrdpg_compute_G_in_vectorized_cpp`, i, X, Y, Z, tau)
}

#' Fast C++ implementation of psi1 function
#'
#' Smoothed log(x) function: quadratic for x < tau, log(x) otherwise
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi1(x)
#' @export
psi1_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_psi1_cpp`, x, tau)
}

#' Fast C++ implementation of psi2 function
#'
#' Smoothed log(1-x) function: log(1-x) for x <= 1-tau, quadratic otherwise
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi2(x)
#' @export
psi2_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_psi2_cpp`, x, tau)
}

#' Fast C++ implementation of psi function
#'
#' psi(x) = psi1(x) - psi2(x)
#'
#' @param s numeric vector of inner products
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi(s)
#' @export
psi_cpp <- function(s, tau = 0.05) {
    .Call(`_cgrdpg_psi_cpp`, s, tau)
}

#' Fast C++ implementation of dpsi1 (derivative of psi1)
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi1'(x)
#' @export
dpsi1_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_dpsi1_cpp`, x, tau)
}

#' Fast C++ implementation of dpsi2 (derivative of psi2)
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi2'(x)
#' @export
dpsi2_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_dpsi2_cpp`, x, tau)
}

#' Fast C++ implementation of dpsi (derivative of psi)
#'
#' dpsi(x) = dpsi1(x) - dpsi2(x)
#'
#' @param s numeric vector of inner products
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi'(s)
#' @export
dpsi_cpp <- function(s, tau = 0.05) {
    .Call(`_cgrdpg_dpsi_cpp`, s, tau)
}

#' Fast C++ implementation of ddpsi1 (second derivative of psi1)
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi1''(x)
#' @export
ddpsi1_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_ddpsi1_cpp`, x, tau)
}

#' Fast C++ implementation of ddpsi2 (second derivative of psi2)
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi2''(x)
#' @export
ddpsi2_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_ddpsi2_cpp`, x, tau)
}

#' Fast C++ implementation of ddpsi (second derivative of psi)
#'
#' ddpsi(x) = ddpsi1(x) - ddpsi2(x)
#'
#' @param s numeric vector of inner products
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of psi''(s)
#' @export
ddpsi_cpp <- function(s, tau = 0.05) {
    .Call(`_cgrdpg_ddpsi_cpp`, s, tau)
}

#' Fast C++ implementation of Psi1 (integral of psi1)
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of Psi1(x)
#' @keywords internal
Psi1_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_Psi1_cpp`, x, tau)
}

#' Fast C++ implementation of Psi2 (integral of psi2)
#'
#' @param x numeric vector
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of Psi2(x)
#' @keywords internal
Psi2_cpp <- function(x, tau = 0.05) {
    .Call(`_cgrdpg_Psi2_cpp`, x, tau)
}

#' Fast C++ implementation of Psi (integral of psi)
#'
#' Psi(x) = Psi1(x) - Psi2(x)
#'
#' @param s numeric vector of inner products
#' @param tau smoothing parameter (default 0.05)
#' @return numeric vector of Psi(s)
#' @export
Psi_cpp <- function(s, tau = 0.05) {
    .Call(`_cgrdpg_Psi_cpp`, s, tau)
}

